################### USERS
GET http://localhost:3000/users
###
GET http://localhost:3000/users/4
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Matheus",
    "email": "matheus@email.com",
    "telephone": "21980679807",
    "road": "Caracas",
    "neighborhood": "Bento Ribeiro",
    "city": "Rio de Janeiro",
    "number": 17,
    "complement": "Casa 2",
    "zip_code": 21331740,
    "is_admin":  true
}
###
PATCH http://localhost:3000/users/4
Content-Type: application/json

{
    "name": "Matheus2"
}
###
DELETE http://localhost:3000/users/1

################### AUTH
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "matheus@email.com",
    "password": "123456"
}
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Matheus",
    "email": "matheus@email.com",
    "telephone": "21980679807",
    "road": "Caracas",
    "neighborhood": "Bento Ribeiro",
    "city": "Rio de Janeiro",
    "number": 17,
    "complement": "Casa 2",
    "zip_code": 21331740,
    "is_admin":  true,
    "password": "123456"
}

###
POST http://localhost:3000/auth/forget
Content-Type: application/json

{
    "email": "matheus@email.com"
}

###
POST http://localhost:3000/auth/reset
Content-Type: application/json

{
    "password": "654321",
    "token": "teste.teste.teste"
}


